extends Node

signal card_played(card_data: Resource, targets: Array)
signal damage_dealt(source: Variant, target: Variant, amount: int, damage_type: String)
signal block_gained(entity: Variant, amount: int)
signal turn_started(turn_number: int)
signal turn_ended()
signal player_turn_started()
signal player_turn_ended()
signal enemy_turn_started()
signal enemy_turn_ended()
signal enemy_died(enemy: Variant)
signal combat_won()
signal combat_lost()
signal status_applied(entity: Variant, status_id: String, stacks: int)
signal status_removed(entity: Variant, status_id: String)
signal card_drawn(card_data: Resource)
signal card_discarded(card_data: Resource)
signal card_exhausted(card_data: Resource)
signal energy_changed(current: int, max_energy: int)
signal hp_changed(entity: Variant, current_hp: int, max_hp: int)
signal relic_triggered(relic_id: String, event_name: String)
